editorconfig: true
printWidth: 100
tabWidth: 2
semi: true
trailingComma: all
arrowParens: always
singleQuote: true
bracketSpacing: true
bracketSameLine: false
embeddedLanguageFormatting: off
pluginSearchDirs: false
importOrderSeparation: true
importOrderSortSpecifiers: true
importOrderGroupNamespaceSpecifiers: true
importOrderMergeDuplicateImports: true
importOrderCombineTypeAndValueImports: true
importOrderBuiltinModulesToTop: true
importOrder:
  - '^[./]'
plugins:
  - '@ianvs/prettier-plugin-sort-imports'
  - prettier-plugin-jsdoc
